# Secret - Stores sensitive data like passwords, tokens, and keys
# Secrets are base64 encoded and can be mounted as files or environment variables
# ⚠️  IMPORTANT: Never commit real secrets to Git! This is just a sample.
apiVersion: v1             # API version for Secret
kind: Secret              # Resource type - stores sensitive data
metadata:                 # Information about this Secret
  name: app-secrets       # Name of the Secret
  namespace: default      # Kubernetes namespace
  labels:                 # Labels to organize this resource
    app: task-manager
    type: credentials
type: Opaque              # Secret type - Opaque means arbitrary user-defined data
data:                     # Secret data - all values must be base64 encoded
  # Database credentials (base64 encoded)
  DB_USERNAME: ZGJ1c2Vy        # "dbuser" in base64
  DB_PASSWORD: c2VjcmV0UGFzcw==  # "secretPass" in base64