name: Simple Workflow

on: [push]  # Runs whenever you push code

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Get your code
      - run: ls -la                # List all files in the repo

