name: CD Pipeline - Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/task-manager:latest
            ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image info
        run: |
          echo "🚀 Docker image built and pushed successfully!"
          echo "📦 Repository: ${{ vars.DOCKER_USERNAME }}/task-manager"
          echo "🏷️  Tags: latest, ${{ github.sha }}"
          echo ""
          echo "⚡ Quick start command:"
          echo "docker pull ${{ vars.DOCKER_USERNAME }}/task-manager:latest"
          echo "docker run -p 8000:8000 ${{ vars.DOCKER_USERNAME }}/task-manager:latest"
          echo ""
          echo "🔗 View on Docker Hub: https://hub.docker.com/r/${{ vars.DOCKER_USERNAME }}/task-manager"