# .github/workflows/manual-python.yml
name: Manual Python Workflow
on:
  workflow_dispatch:        # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v5

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Show Python version
      - name: Python version
        run: python --version
