name: Second Test Workflow
on: [push, pull_request]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Message
        run: echo "Hello World"

  python-version:
    runs-on: ubuntu-latest
    steps: 
      - name: Python version
        run: python --version