name: Simple Workflow

on:
  push:
    branches:
      - cicd

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello! GitHub Actions is running successfully ✅"

